garlic_blog_app:
    resource: "@GarlicBlogAppBundle/Controller/"
    type:     annotation
    prefix:   /

garlic_blog_login:
    resource: "@GarlicBlogLoginBundle/Controller/"
    type:     annotation
    prefix:   /

