garlic_blog_app:
    resource: "@GarlicBlogAppBundle/Controller/"
    type:     annotation
    prefix:   /

garlic_blog_user:
    resource: "@GarlicBlogUserBundle/Controller/"
    type:     annotation
    prefix:   /

